config/routes.rb
Rails.application.routes.draw do
  resources :commentis, only: [:create]
  resources :proyectos
  resources :categories
  resources :comment_photos
  resources :comment_books
  get 'users/edit'
  resources :users, only: [:update]
  get "perfil", to:"users#edit"
  get 'books/index'
  get 'books/new'
  get 'books/show'
  get 'books/edit'
  resources :books
  resources :photos
  get 'my_photos', to: 'photos#my_photos', as: 'my_photos'
  devise_for :users
  get 'home/index'
  resources :articles
  get 'bienvenida', to:"home#index"
  root to: "home#index"
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_rich_text :content
	has_many :commentis, as: :commentable
    has_many :comments
    has_many :has_categories
    has_many :categories, through: :has_categories #(through significa a través de.)
    attr_accessor :category_elements
	def save_categories
    	#categy_elements 1,2,3
    	#concertir eso en un arreglo 1,2,3 => [1,2,3]
    	#categories_array = category_elements.split(",") #esto no hace falta al tener el checkbox
    	# iterar ese arreglo
    	return has_categories.destroy_all if category_elements.nil? || category_elements.empty?

    	has_categories.where.not(category_id: category_elements).destroy_all
    	category_elements.each do |category_id|
    		# crear HasCategory HasCategory<article_id: 1, category_id: 2>
				HasCategory.find_or_create_by(article: self,category_id: category_id)
		end
	end
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :comment_books
    has_many :commentis, as: :commentable
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :has_categories
    has_many :articles, through: :has_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/comment_book.rb
class CommentBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/comment_photo.rb
class CommentPhoto < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/commenti.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    enum license: [:copyright, :copyleft, :creative_comons]
    enum visibility:[:pub, :priv]
    has_many :comment_photos
    has_many :commentis, as: :commentable
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_one_attached :avatar
  has_many :comments
  has_many :photos
  has_many :comment_photos
  has_many :comment_books
  has_many :commentis
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: %i[ show edit update destroy ]

  # GET /proyectos or /proyectos.json
  def index
    @proyectos = Proyecto.all
  end

  # GET /proyectos/1 or /proyectos/1.json
  def show
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos or /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @post.save
        PostMailer.with(user: current_user, post: @post).post_created.deliver_later
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1 or /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to @proyecto, notice: "Proyecto was successfully updated." }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1 or /proyectos/1.json
  def destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: "Proyecto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proyecto_params
      params.require(:proyecto).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/commenti_helper.rb
module CommentiHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
    # si se cumple, el usuario autenticado podrá ver sus fotos o las fotos públicas
    # si no se cumple, el usuario no autenticado verá solamente las fotos públicas
    def get_possible_photos
        if current_user
                @possible_photos = Photo.where(user: current_user).or(Photo.where(visibility: :pub))
            else
                @possible_photos = Photo.where(visibility: :pub)
            end
            return @possible_photos
    end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/proyectos/_form.html.erb
<%= form_with(model: proyecto) do |form| %>
  <% if proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
        <% proyecto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h1>Editing Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>

app/views/proyectos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyectos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyectos.each do |proyecto| %>
      <tr>
        <td><%= proyecto.title %></td>
        <td><%= proyecto.content %></td>
        <td><%= link_to 'Show', proyecto %></td>
        <td><%= link_to 'Edit', edit_proyecto_path(proyecto) %></td>
        <td><%= link_to 'Destroy', proyecto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyecto', new_proyecto_path %>

app/views/proyectos/new.html.erb
<h1>New Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Back', proyectos_path %>

app/views/proyectos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @proyecto.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @proyecto.content %>
</p>

<%= link_to 'Edit', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Back', proyectos_path %>