config/routes.rb
Rails.application.routes.draw do
  resources :commentis, only: [:create]
  resources :proyectos
  resources :categories
  resources :comment_photos
  resources :comment_books
  get 'users/edit'
  resources :users, only: [:update]
  get "perfil", to:"users#edit"
  get 'books/index'
  get 'books/new'
  get 'books/show'
  get 'books/edit'
  resources :books
  resources :photos
  get 'my_photos', to: 'photos#my_photos', as: 'my_photos'
  devise_for :users
  get 'home/index'
  resources :articles
  get 'bienvenida', to:"home#index"
  root to: "home#index"
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_rich_text :content
	has_many :commentis, as: :commentable
    has_many :comments
    has_many :has_categories
    has_many :categories, through: :has_categories #(through significa a través de.)
    attr_accessor :category_elements
	def save_categories
    	#categy_elements 1,2,3
    	#concertir eso en un arreglo 1,2,3 => [1,2,3]
    	#categories_array = category_elements.split(",") #esto no hace falta al tener el checkbox
    	# iterar ese arreglo
    	return has_categories.destroy_all if category_elements.nil? || category_elements.empty?

    	has_categories.where.not(category_id: category_elements).destroy_all
    	category_elements.each do |category_id|
    		# crear HasCategory HasCategory<article_id: 1, category_id: 2>
				HasCategory.find_or_create_by(article: self,category_id: category_id)
		end
	end
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :comment_books
    has_many :commentis, as: :commentable
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :has_categories
    has_many :articles, through: :has_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/comment_book.rb
class CommentBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/comment_photo.rb
class CommentPhoto < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/commenti.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    enum license: [:copyright, :copyleft, :creative_comons]
    enum visibility:[:pub, :priv]
    has_many :comment_photos
    has_many :commentis, as: :commentable
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_one_attached :avatar
  has_many :comments
  has_many :photos
  has_many :comment_photos
  has_many :comment_books
  has_many :commentis
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  
  def new
    @book = Book.new
  end  
  def show
   @book = Book.find(params[:id])
  end

  def index

    @books = Book.order("title DESC")
    @books = Book.paginate(:page=>params[:page],per_page:6).order("created_at desc")   

    if params[:title].present?
      @books = @books.where("title LIKE ?", "%#{params[:title]}%")



    elsif params[:title] == params[:title].nil?
      flash[:notice] = "No hay coincidencias"
 

    end

  end

  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
  if @book.update(book_params)
    redirect_to @book
  else
    render :edit
  end
  end
    def create
      @book = Book.new(book_params)
      @book.user = current_user
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy

    flash[:notice] = "El libro ha sido eliminado exitosamente"
    redirect_to books_path
  end

private
  def book_params
    params.require(:book).permit(:title, :author, :description, :image_url, :publication_date, :price. :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/commenti_helper.rb
module CommentiHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
    # si se cumple, el usuario autenticado podrá ver sus fotos o las fotos públicas
    # si no se cumple, el usuario no autenticado verá solamente las fotos públicas
    def get_possible_photos
        if current_user
                @possible_photos = Photo.where(user: current_user).or(Photo.where(visibility: :pub))
            else
                @possible_photos = Photo.where(visibility: :pub)
            end
            return @possible_photos
    end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_comment_books.html.erb
<div class="card comments mt-5 mb-5">
  <div class="card-header border-bottom-0 font-weight-bold bg-transparent">Comentarios</div>
  <ul class="list-group list-group-flush">
    <% @book.comment_books.each do |comment| %>
      <li class="list-group-item">
        <header class="comment-header"><strong><%= comment.user.email %></strong> wrote <%= distance_of_time_in_words(Time.current, comment.created_at) %> ago</header>
        <div class="comment-body"><%= comment.body %></div>
      </li>
    <% end %>

    <% if @book.comment_books.empty? %>
      <li class="list-group-item text-center">Aún no hay comentarios para este artículo :(</li>
    <% end %>
  </ul>
</div>

<% if signed_in? %>
  <div class="card bg-light new-comment">
    <div class="card-body">
      <p class="font-weight-bold">Deja tu comentario:</p>
      <%= form_for @book.comment_books.build do |f| %>
        <%= f.hidden_field :book_id, value: @book.id %>
        <div class="form-group">
          <%= f.text_area :body, rows: 4, class: "form-control" %>
        </div>

        <div class="text-right">
          <%= f.submit "Comentar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="card bg-light mt-5">
    <div class="card-body">
      <p class="card-text text-center lead"><%= link_to "Regístrate", new_user_registration_path %> o <%= link_to "Ingresa", new_user_session_path %> para comentar</p>
    </div>
  </div>
<% end %>

app/views/books/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div class="card mt-5">
        <div class="card-header font-weight-bold"><%= title %></div>
        <%= form_for @book do |f| %>
        <div class="card-body">
          <% if @book.errors.any? %>
            <div id="card border-0">
              <p>This form contains <%= pluralize(@book.errors.count, "error") %>:</p>
              <ul>
              <% @book.errors.full_messages.each do |msg| %>
                <li class="text-danger"><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :author %>
            <%= f.text_field :author, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 4, class: "form-control" %>
          </div>


          
          <div class="form-group">

            <%= f.label :image_url %>
            <%= f.url_field :image_url, class: "form-control" %>
           
          </div>


          <div class="form-group">
            <%= f.label :publication_date %>
            <%= f.date_field :publication_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class: "form-control", step: :any %>
          </div>

        </div>
        <div class="card-footer text-right">
          <%= link_to "Cancelar", books_path, class: "btn btn-default" %>
          <%= f.submit class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<%= render "form", title: "Agregar Libro" %>

app/views/books/index.html.erb
<div class="books-page">
  <div class="container">



<%= form_tag books_path, method: :get do %>
    <div class="row">
      <div class="form-group col-4 col-md-4">
        <%= text_field_tag :title, params[:title], class: "form-control", placeholder: "¿qué estás buscando?" %>
      </div>
      <div class="form-group col-6 col-md-4">
          <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
      </div>
    <div class="text-right"><%= link_to "Agregar Libro", new_book_path, class: "btn btn-success rounded-3" %></div>
    <% end %>  
    </div>


    <section>
      <% if flash[:notice] %>
        <p class="alert alert-info"> <%= notice %> </p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert alert-danger"> <%= alert  %> </p>
      <% end %>
      <%= yield %>
    </section>

  <div class="container">
  <div class="row row-cols-1">



    <% @books.each do |book| %>



      <div class="book card flex-sm-row align-items-center align-items-sm-start mt-1">
        <img src="<%= book.image_url %>" alt="<%= book.title %>" class="border border-dark">
        <div class="card-body">
          <h5 class="card-title">
            <%= book.title %>
            <small><%= book.author %></small>
          </h5>
          <p class="card-text"><%= book.description %></p>

          <%= link_to "Detalles", book, class: "btn btn-primary btn-sm" %>

          <% if signed_in? %>

            <%= link_to "  Editar  ", edit_book_path(book), class: "btn btn-info btn-sm" %>

            <%= link_to "Eliminar", book, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>

            

          <% end %>
        </div>
      </div>
    <% end %>

</div>
</div>

    <%#= will_paginate @books,renderer: BootstrapPagination::Rails %>

    <div class="pagination" style="font-size: small">
      <%#= will_paginate @books,
      :inner_window => 1,
      :outer_window => 1,
:separator      => "&laquo ",
      :previous_label => '  Anterior -  ',
      :next_label => ' - Página siguiente EEE  '
      %>
<%= 
will_paginate @books,
  :class          => 'pagination',
  :previous_label => ' &laquo; Anterior ',
  :next_label     => ' Siguiente &raquo; ',
  :inner_window   => 4, # links around the current page
  :outer_window   => 1, # links around beginning and end
  :separator      => ' - ', # single space is friendly to spiders and non-graphic browsers
  :param_name     => :page,
  :params         => nil,
  
  :page_links     => true,
  :container      => true

%>
    </div>

  </div>
</div>

app/views/books/new.html.erb
<%= render "form", title: "Editar Libro" %>

app/views/books/show.html.erb
<div class="book-page">
  <div class="container">
    <%= link_to "&larr; Volver".html_safe, books_path, class: "btn btn-link" %>

    <header class="main">
      <h2><%= @book.title %></h2>
      <div class="author"><%= @book.author %></div>
    </header>

    <div class="book d-flex flex-sm-row align-items-center align-items-sm-start">
      <img src="<%= @book.image_url %>" alt="<%= @book.title %>">
      <div class="book-details">
        <p><%= @book.description %></p>
        <dl>
          <dt>Fecha de publicación</dt>
          <dd><%= @book.publication_date %></dd>
          <dt>Precio</dt>
          <dd><%= @book.price %></dd>
        </dl>
        <div class="text-right">
          <% if signed_in? %>
            <%= link_to "Editar", edit_book_path(@book), class: "btn btn-link" %>
            <%= link_to "Eliminar", @book, class: "btn btn-link text-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>
          <% end %>
        </div>
        <%= render "comment_books" %>
      </div>
    </div>
  </div>
</div>
<div class="card comments mt-5 mb-5">
  <div class="card-header border-bottom-0 font-weight-bold bg-transparent">Comentarios</div>
  <ul class="list-group list-group-flush">
    <% if @article.commentis.empty? %>
      <li class="list-group-item text-center">Aún no hay comentarios para este artículo :(</li>
    <% end %>
  </ul>
</div>
<%= render 'commentis/widget', commentable: @book%>